### PR TITLE
Plenary series updates

### PR DESCRIPTION
**Pull request by ehinrichs**
Added Plenary series to resources. Added 2024 and 2023 speakers. Plenary titles link to page with abstract/bio/picture. Will eventually add links to video.

### CODE REVIEW

**Comment by jd-moulton** [comment]
There are a few updates that I think you should make before we merge this PR:

- Each plenary speaker should have their position, department/group, institution provided (below their name) on the page with the abstract.
- The slides should be in pdf, if they provide them to us in pptx, just create a pdf and upload that
- The slides can be stored in the local github repo (we shouldn't point to the Google Drive for these).

Under resources the "Plenary" entry should be something like "Plenary Seminars", or Plenaries (plural).  Granted we have "Seminars (Internal)" as the first entry.   So maybe the first entry should be "Internal Seminars" and this one should be "Plenary Seminars".

**Comment by ehinrichs** [comment]
@jd-moulton Updated the branch to include your suggestions. Take a look and let me know what you think.

-Erica

**Comment by jd-moulton** [comment]
Looks good, let's just reorder the entries under Resources since the seminars are so similar now:

- Internal Seminars
- Plenary Seminars
- Team Meetings
- Events
- IDEAS-Watersheds Brochure

<beak of some kind> maybe with heading external
- HPC Best Practices (on IDEAS-ECP website)

Then we can add other external links as well, but there won't be any confusion about which links take you to a different web site.

**Comment by ehinrichs** [comment]
@jd-moulton Updates to resources order is complete.

**Comment by jd-moulton** [comment]
Looking at the leadership team, I see we still have Nicole Jeffrey as the project coordinator.   We should drop that entry from the list.  For now I think we should leave project coordinator out, but we may put back as TBD or something.  
... oops this may be in the other PR.

**Comment by ehinrichs** [comment]
@jd-moulton That change is on the ehinrichs/web_dev branch along with the changes to the team members (photos etc). You might want to push that branch first, and then this one.

**Comment by jd-moulton** [comment]
No worries, lets get this one done and I'll look at the other one this afternoon.

**Review by jd-moulton — APPROVED** [review]
Changes seem complete, and its working for me.

**Pull request merged**
